name: Deploy React App
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Start test runner
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Start eslint runner
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
