name: Pull Request Details
on:
  pull_request:
    types: [opened, closed]
    branches:
      - 'develop'
      - 'feature/**'
      - 'bugfix/**'
      - 'improve/**'
jobs:
  pr_details:
    runs-on: ubuntu-latest
    steps:
      - name: Show Pull Request Details
        run: echo "${{ toJSON(github.event) }}"
