name: Pull Request Details
on:
  pull_request:
    types: [opened, closed]
    branches:
      - main
jobs:
  pr_details:
    runs-on: ubuntu-latest
    steps:
      - name: Print Pull Request Details
        run: echo "${{ toJSON(github.event) }}"
